/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Forum {
      
    export type CommentStruct = {id: BigNumberish, postId: BigNumberish, parentCommentId: BigNumberish, author: AddressLike, contentHash: BytesLike, timestamp: BigNumberish, likeCount: BigNumberish}

    export type CommentStructOutput = [id: bigint, postId: bigint, parentCommentId: bigint, author: string, contentHash: string, timestamp: bigint, likeCount: bigint] & {id: bigint, postId: bigint, parentCommentId: bigint, author: string, contentHash: string, timestamp: bigint, likeCount: bigint }
  

    export type PostStruct = {id: BigNumberish, author: AddressLike, contentHash: BytesLike, timestamp: BigNumberish, likeCount: BigNumberish, commentCount: BigNumberish}

    export type PostStructOutput = [id: bigint, author: string, contentHash: string, timestamp: bigint, likeCount: bigint, commentCount: bigint] & {id: bigint, author: string, contentHash: string, timestamp: bigint, likeCount: bigint, commentCount: bigint }
  
    }

  export interface ForumInterface extends Interface {
    getFunction(nameOrSignature: "commentCount" | "createComment" | "createPost" | "getCommentReplies" | "getPost" | "getPostComments" | "getPosts" | "hasLikedComment" | "hasLikedPost" | "likeComment" | "likePost" | "postCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CommentCreated" | "CommentLiked" | "PostCreated" | "PostLiked"): EventFragment;

    encodeFunctionData(functionFragment: 'commentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'createComment', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'createPost', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCommentReplies', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPostComments', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPosts', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasLikedComment', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasLikedPost', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'likeComment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'likePost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'postCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'commentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommentReplies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPostComments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPosts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasLikedComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasLikedPost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'likeComment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'likePost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postCount', data: BytesLike): Result;
  }

  
    export namespace CommentCreatedEvent {
      export type InputTuple = [commentId: BigNumberish, postId: BigNumberish, parentCommentId: BigNumberish, author: AddressLike, contentHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [commentId: bigint, postId: bigint, parentCommentId: bigint, author: string, contentHash: string, timestamp: bigint];
      export interface OutputObject {commentId: bigint, postId: bigint, parentCommentId: bigint, author: string, contentHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommentLikedEvent {
      export type InputTuple = [commentId: BigNumberish, liker: AddressLike, newLikeCount: BigNumberish];
      export type OutputTuple = [commentId: bigint, liker: string, newLikeCount: bigint];
      export interface OutputObject {commentId: bigint, liker: string, newLikeCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostCreatedEvent {
      export type InputTuple = [postId: BigNumberish, author: AddressLike, contentHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [postId: bigint, author: string, contentHash: string, timestamp: bigint];
      export interface OutputObject {postId: bigint, author: string, contentHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PostLikedEvent {
      export type InputTuple = [postId: BigNumberish, liker: AddressLike, newLikeCount: BigNumberish];
      export type OutputTuple = [postId: bigint, liker: string, newLikeCount: bigint];
      export interface OutputObject {postId: bigint, liker: string, newLikeCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Forum extends BaseContract {
    
    connect(runner?: ContractRunner | null): Forum;
    waitForDeployment(): Promise<this>;

    interface: ForumInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    commentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createComment: TypedContractMethod<
      [_postId: BigNumberish, _parentCommentId: BigNumberish, _contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    createPost: TypedContractMethod<
      [_contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    getCommentReplies: TypedContractMethod<
      [_commentId: BigNumberish, ],
      [Forum.CommentStructOutput[]],
      'view'
    >
    

    
    getPost: TypedContractMethod<
      [_postId: BigNumberish, ],
      [Forum.PostStructOutput],
      'view'
    >
    

    
    getPostComments: TypedContractMethod<
      [_postId: BigNumberish, ],
      [Forum.CommentStructOutput[]],
      'view'
    >
    

    
    getPosts: TypedContractMethod<
      [_offset: BigNumberish, _limit: BigNumberish, ],
      [[Forum.PostStructOutput[], bigint] & {posts: Forum.PostStructOutput[], total: bigint }],
      'view'
    >
    

    
    hasLikedComment: TypedContractMethod<
      [_user: AddressLike, _commentId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    hasLikedPost: TypedContractMethod<
      [_user: AddressLike, _postId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    likeComment: TypedContractMethod<
      [_commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    likePost: TypedContractMethod<
      [_postId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    postCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'commentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createComment'): TypedContractMethod<
      [_postId: BigNumberish, _parentCommentId: BigNumberish, _contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createPost'): TypedContractMethod<
      [_contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCommentReplies'): TypedContractMethod<
      [_commentId: BigNumberish, ],
      [Forum.CommentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPost'): TypedContractMethod<
      [_postId: BigNumberish, ],
      [Forum.PostStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPostComments'): TypedContractMethod<
      [_postId: BigNumberish, ],
      [Forum.CommentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPosts'): TypedContractMethod<
      [_offset: BigNumberish, _limit: BigNumberish, ],
      [[Forum.PostStructOutput[], bigint] & {posts: Forum.PostStructOutput[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasLikedComment'): TypedContractMethod<
      [_user: AddressLike, _commentId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasLikedPost'): TypedContractMethod<
      [_user: AddressLike, _postId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'likeComment'): TypedContractMethod<
      [_commentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'likePost'): TypedContractMethod<
      [_postId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'postCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'CommentCreated'): TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
getEvent(key: 'CommentLiked'): TypedContractEvent<CommentLikedEvent.InputTuple, CommentLikedEvent.OutputTuple, CommentLikedEvent.OutputObject>;
getEvent(key: 'PostCreated'): TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
getEvent(key: 'PostLiked'): TypedContractEvent<PostLikedEvent.InputTuple, PostLikedEvent.OutputTuple, PostLikedEvent.OutputObject>;

    filters: {
      
      'CommentCreated(uint256,uint256,uint256,address,bytes32,uint256)': TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
      CommentCreated: TypedContractEvent<CommentCreatedEvent.InputTuple, CommentCreatedEvent.OutputTuple, CommentCreatedEvent.OutputObject>;
    

      'CommentLiked(uint256,address,uint256)': TypedContractEvent<CommentLikedEvent.InputTuple, CommentLikedEvent.OutputTuple, CommentLikedEvent.OutputObject>;
      CommentLiked: TypedContractEvent<CommentLikedEvent.InputTuple, CommentLikedEvent.OutputTuple, CommentLikedEvent.OutputObject>;
    

      'PostCreated(uint256,address,bytes32,uint256)': TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
      PostCreated: TypedContractEvent<PostCreatedEvent.InputTuple, PostCreatedEvent.OutputTuple, PostCreatedEvent.OutputObject>;
    

      'PostLiked(uint256,address,uint256)': TypedContractEvent<PostLikedEvent.InputTuple, PostLikedEvent.OutputTuple, PostLikedEvent.OutputObject>;
      PostLiked: TypedContractEvent<PostLikedEvent.InputTuple, PostLikedEvent.OutputTuple, PostLikedEvent.OutputObject>;
    
    };
  }