/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Forum } from './Forum.js';
export * as factories from './factories/index.js';
export { Forum__factory } from './factories/Forum__factory.js';